#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI-SFT1200

on:
  # push:
  #   branches: 
  #     - master
  schedule:
    - cron: 0 20 * * *
  # release:
  #   types: [published]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout openwrt repo
        uses: actions/checkout@v3
        with:
          repository: gl-inet/gl-infra-builder

      - name: Checkout diffconfig repo
        uses: actions/checkout@v3
        with:
          path: diffconfig

      - name: Checkout openwrt-openwrt repo
        uses: actions/checkout@v3
        with:
          path: openwrt-openwrt
          repository: openwrt/openwrt
      
      - name: Checkout openwrt-packages repo
        uses: actions/checkout@v3
        with:
          path: openwrt-packages
          repository: openwrt/packages
      
      - name: Build system setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python2.7-dev python3 unzip wget \
            python3-distutils-extra python3-setuptools python3-dev rsync subversion \
            swig time xsltproc zlib1g-dev
          sudo apt-get install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
            git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
            mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
            rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo apt-get install -y wget file subversion sudo python3-yaml
          sudo apt-get install -y build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev
      
      - name: Checkout Siflower
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git config --global user.name "A"
          git config --global user.email "a@gmail.com"
          git config --global core.editor "vi"
          python3 setup.py -c configs/config-siflower-18.x.yml

      - name: Checkout Siflower
        env:
          DEBIAN_FRONTEND: noninteractive
        working-directory: ./openwrt-18.06/siflower/openwrt-18.06/
        run: |
          ./scripts/gen_config.py target_siflower_gl-sft1200


      - name: Update feeds
        working-directory: ./openwrt-18.06/siflower/openwrt-18.06/
        run: |
          sed -i "/helloworld/d" "feeds.conf.default"
          echo "src-git helloworld https://github.com/fw876/helloworld.git;main" >> "feeds.conf.default"
          ./scripts/feeds update -a
          mkdir feeds/helloworld/trojan/patches
          wget https://github.com/xiaorouji/openwrt-passwall/raw/packages/trojan/patches/001-force-openssl-version.patch -O feeds/helloworld/trojan/patches/001-force-openssl-version.patch
          ./scripts/feeds install -a

      - name: Update golang & zerotier packages
        run: |
          rm -rf ./openwrt-18.06/siflower/openwrt-18.06/feeds/packages/net/zerotier/*
          cp -r ./openwrt-packages/net/zerotier/* ./openwrt-18.06/siflower/openwrt-18.06/feeds/packages/net/zerotier/
          rm -rf ./openwrt-18.06/siflower/openwrt-18.06/feeds/packages/lang/golang/*
          cp -r ./openwrt-packages/lang/golang/* ./openwrt-18.06/siflower/openwrt-18.06/feeds/packages/lang/golang/

      - name: Generate configuration file
        run: |
          cat ./diffconfig/diffconfig/sft1200ssrplus.config >> ./openwrt-18.06/siflower/openwrt-18.06/.config

      - name: Compile firmware
        working-directory: ./openwrt-18.06/siflower/openwrt-18.06/
        run: |
          make defconfig
          make -j1 download
          make -j1 V=s


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt firmware SFT1200
          path: ./openwrt-18.06/siflower/openwrt-18.06/bin/
