#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI-GHL-OpenWrt

on:
  # push:
  #   branches: 
  #     - master
  schedule:
    - cron: '0 20 * * *'
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout openwrt repo
        uses: actions/checkout@v3
        with:
          repository: openwrt/openwrt

      - name: Checkout diffconfig repo
        uses: actions/checkout@v3
        with:
          path: diffconfig
      
      - name: Build system setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex g++ gawk gcc-multilib gettext \
            git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev
          sudo apt install -y wget file subversion sudo

      - name: Update feeds
        run: |
          sed -i "/helloworld/d" "feeds.conf.default"
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> "feeds.conf.default"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          cp ./diffconfig/diffconfig/GHLo.config .config

      - name: Build the firmware image
        run: |
          make -j $(($(nproc)+1)) defconfig download clean world

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt firmware GHL-OpenWrt
          path: ./bin/
